### ISSUE TITLE
Assigned subjects page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#18]
![screen shot 2014-03-05 at 4 53 11 pm](https://f.cloud.github.com/assets/5439311/2339037/96891d56-a4b0-11e3-8100-cd8e4ba01601.png)

it can also be realized: that if there is no subjects, then do not show the table, but just show the title:

**Comment by jrhorn424** [comment]
> ## Do you need the sql code which will find the subjects which are
> 
> assigned?

No, thanks for asking. Is this a feature you think is worth bringing 
over from ORSEE?

I imagined we would start a recruitment cycle, select from a sub pool, 
and click "invite". That would load the selected subjects' email 
addresses into memory and fire off the e-mail. There's not a lot that 
needs to be persisted, so I want to question even the need to view this 
kind of data.

**Comment by mlfreer** [comment]
the idea that assign button can work in this way also:
so you can add assigned subjects and then send invitations for all who were not participated.
i think that in such way it is a bit more flexible, cause some people will prefer to use the ORSEE style recruiting and some the one you mentioned

**Comment by jrhorn424** [comment]
I'm not sure I understand what you mean. If you mean that we need a way to re-recruit for the same or a different session with the same subpool, I'd agree. I should have emphasized that the important question is whether or not this ought to be exposed as a page in the interface?

Would you ever edit a subpool were generating a different subpool would suffice?

Something we have to keep in mind is subject comments and ban status. Those sorts of things ought to be managed by admins, in my opinion, not experimenters. I'm open to being convinced otherwise.

What I'm imagining is that (as an experimenter) you select a session when beginning recruitment. Then you select your subpool based on criteria you specify. Then you click invite. Nowhere do you need to actually see who is in the subpool.

When you start another session, you being recruitment by selecting from a subpool based on criteria you specify. Then you click invite. If someone has already participated, the system does not send them an e-mail. That's something that should be automated and baked in.

**Comment by mlfreer** [comment]
yes we need to re-recruit and the list is better to make visible only for admins,
we need the page at least for admins, because sometimes it is necessary to force subjects,
i'll think on it and possibly restate this task:
like adding button (link) assin subjects for the experiment 
and creating the page like this, which is visible only for admins

**Comment by mlfreer** [comment]
We need this page for admin, just without button **assign subjects**
and with link (or button): **back to experiment** in the bottom of the page
cause as i mentioned earlier sometimes it is necessary to force subjects

**Comment by mlfreer** [comment]
it has low priority, so we will implement it later
