### ISSUE TITLE
Corrections on SP page

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#38]
![screen shot 2014-03-30 at 5 18 32 pm](https://cloud.githubusercontent.com/assets/5439311/2562549/3d9a6f10-b851-11e3-9489-6d46d92a1036.png)

1) add total number of sp to the table
2) add error message if you want to assign more subjects than it is in DB

**Comment by jrhorn424** [comment]
That's looking great. If we want to make criteria dynamic in the future, 
I'd have a look at 
[ransack](https://github.com/activerecord-hackery/ransack). It makes it 
trivial to create new criteria when new columns are added to the model, 
and also allows you to dynamically add new filters like:

```
 Major: Economics OR
 Major: Physical Sciences
```

**Comment by ppodolsky** [comment]
Thanks, Jeffrey, this gem can be really useful under some conditions. 
Unfortunately, there are some issues.
1) I wasn't be able to find functionality for creating BETWEEN where clauses in this gem. Two "less or equal" conditions are a bad trade-off, because I traced some performance troubles with the execution plan in Postgres 9.2
2) It is useless for complex queries like we have. Calculating attendance parameter requires inlined SQL, which cannot be expressed even by Rails Model.

**Comment by jrhorn424** [comment]
On 31 Mar 2014, at 15:19, Pasha Podolsky wrote:

> Thanks, Jeffrey, this gem can be really useful under some conditions.
> Unfortunately, there are some issues. 1) I wasn't be able to find 
> functionality for creating BETWEEN where clauses in this gem. 2) It is 
> useless for complex queries like we have. Calculating attendance 
> parameter requires inlined SQL, which cannot be expressed even by 
> Rails Model.

That's unfortunate. I do believe you might be able to write more complex 
queries if you dive into Arel. I'd recommend doing that anyway because 
of the work that is done in the rails framework toward increasing 
security. Exposing SQL in the application layer is usually a "bad idea" 
and when we're afforded more time, it might be a good idea to revisit 
it.

**Comment by ppodolsky** [comment]
I reviewed Arel and still couldn't find a right solution for the query that had been placed in subject_controller.rb. Sometimes relational model cannot be properly mapped onto object model without row-by-row iterating and this is the case.
You should feel free to inspect this query and if you wish - provide a solution/start a branch in Arel/Ransack terms but without row-by-row iterating. We would incorporate it into the project.
