### ISSUE TITLE
Update the current models

### ISSUE THREAD

**Issue by mlfreer** [jrhorn424/recruiter#7]
Objects (in the order of priority) and properties:
**experiment**: 
- id  
- name  
- description  
- public_name  
- type  (field   or lab)  
- is_finished  

**session**:
- id  
- date_start  
- date_finish  
- session_length
- number_of_registered_subjects
- necessary_number_of_subjects
- lab  
- is_finished
- active_for_registration (it is different from the finished, because experimenters are used to create sessions before starting the registration)
- hours_to_finish_registration
- hours_to_reminder

**category**:   
- id  
- tag
# Roles of the user:

**subject** :
- id  
- first_name  
- last_name 
- email
- phone 
- gender  
- ethnicity 
- age  
- class_year  
- total_years  
- year_started  
- current_gpa  
- major 
- years 
- resident
- no_shown_up  
- in_black_list 
- is_active 

**experimenter**:
- id  
- name

**admin**   :
- id  
- name
# 

if you have any additional properties for the objects please mention them.

**Comment by jrhorn424** [comment]
Nice work. Thanks! I'll add the missing parts to the models and push in a bit.

**Comment by jrhorn424** [comment]
I've just pushed a branch for code review. I'll note where I deviated from the request here:
- I was told there would be no need for a public name for the experiment, so any name should be kept private. This will be easy to add if we ever need it.
- I shortened many of the column names to be semantic when used in code, because `Foo.foo_name` isn't as clear as `Foo.name`
- I wasn't clear on why `active_for_registration` was needed. We can talk further about this.

Other notes:
- I used single-table inheritance (STI) for experiment types, since we can easily add any other types in the future by just creating a new, empty model. I'd rather keep this sort of configuration out of the database layer.
- I also used STI for creating user roles rather than having that stored in a table. This will allow us to add specific behavior to roles classes rather than shoving everything in the User model.
- I went with your original implementation on experiment.

Still need to add:
- Blacklist column on User
- Active column on User

That will be completed shortly. I'll also attach an ERD to this ticket for your reference.

**Comment by jrhorn424** [comment]
![models_complete](https://f.cloud.github.com/assets/388761/2378175/cd2c9250-a88b-11e3-909e-b366496fdb3e.png)

**Comment by ppodolsky** [comment]
Is it okay that session has no any linkage to experiment?

**Comment by ppodolsky** [comment]
I don't know the whole workaround, but is it proper that user will be able to have only one role? Does being experimenter exclude the opportunity of being administrator?

**Comment by jrhorn424** [comment]
Paul: Those are good questions. I think of these as nesting roles. Administrator privileges are a strict superset of Experimenter privileges, so only having one role isn't an issue for that reason. If permissions get complicated, then we would require a different solution for roles.

**Comment by jrhorn424** [comment]
@PaulPodolsky What do you mean in terms of linking to experiment? It didn't occur to me to add user_ids to experiments since I was just burning through the list @mlfreer provided. I can add that shortly.
